# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 304a1709171ef3b38b3be9900a1453d9f4114c72a74e31d5bf28f7ae83b8f739ce596c5a2e9f531c549946c742ef587e08d5f81ca7b2b9df0c1edf168df5c1a6

test:
  secret_key_base: 7e18ad261f0bd313a2e4cf91a2ac4313141d93b25b083f2778ccaf80437517fed08b1e4044dffeeaa53555b7b63bdbc0cefdae5bc95ed7361c2bd1f0e4ef4f7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
